# Generated by Django 4.0.4 on 2022-04-16 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_rename_course_name_studentcourses_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=70)),
                ('Teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.teacher')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.courses')),
            ],
        ),
    ]
