# Generated by Django 4.0.4 on 2022-04-16 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='class_name',
        ),
        migrations.AddField(
            model_name='student',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.quiz'),
        ),
    ]
