# Generated by Django 4.0.4 on 2022-04-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
