# Generated by Django 4.0.4 on 2022-04-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_remove_profile_image_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('Image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
