# Generated by Django 4.0.4 on 2022-04-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_profilee_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilee',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
