# Generated by Django 4.0.4 on 2022-04-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_courses_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='quiz_id',
        ),
    ]
