# Generated by Django 4.0.4 on 2022-04-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_classs_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='courses',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=70)),
                ('Teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.teacher')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.courses')),
                ('student_id', models.ManyToManyField(to='Api.student')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='classs',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='Api.classes'),
            preserve_default=False,
        ),
    ]
