# Generated by Django 4.0.4 on 2022-04-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0021_alter_result_marks_alter_result_totall_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_name',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=1),
        ),
    ]
