# Generated by Django 4.0.4 on 2022-04-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_alter_classes_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('Teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.teacher')),
                ('classs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.classes')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.courses')),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Classs',
        ),
        migrations.DeleteModel(
            name='Stu',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='Teach',
        ),
    ]
