# Generated by Django 4.0.4 on 2022-04-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0023_assignment_alter_quiz_file_delete_classs_delete_stu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCourses',
        ),
    ]
