# Generated by Django 4.0.4 on 2022-04-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0024_delete_studentcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='classs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.classes'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='classs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.classes'),
        ),
    ]
