# Generated by Django 4.0.4 on 2022-04-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0026_result_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_material',
        ),
    ]
