# Generated by Django 4.0.4 on 2022-04-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0027_remove_courses_course_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='course',
        ),
        migrations.AddField(
            model_name='classes',
            name='course',
            field=models.ManyToManyField(to='Api.courses'),
        ),
    ]
