# Generated by Django 4.0.4 on 2022-05-21 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0028_remove_classes_course_classes_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('Teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.teacher')),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.classes')),
            ],
        ),
    ]
