# Generated by Django 4.0.4 on 2022-05-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0030_assignmenttwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttwo',
            name='submit_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
