# Generated by Django 4.0.4 on 2022-05-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0031_assignmenttwo_submit_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttwo',
            name='submit_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
