# Generated by Django 4.0.4 on 2022-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0034_quiztwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='submit_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
