# Generated by Django 4.0.4 on 2022-05-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0035_quiz_submit_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submit_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='QuizTwo',
        ),
    ]
