# Generated by Django 4.0.4 on 2022-05-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0036_assignment_submit_file_delete_quiztwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignmenttwo',
        ),
    ]
